Added config file support

diff --git a/gitcrypt b/gitcrypt
--- a/gitcrypt
+++ b/gitcrypt
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-readonly VERSION="0.3.0"
+readonly VERSION="0.3.1"
 readonly DEFAULT_CIPHER="aes-256-ecb"
 
 init_config() {
@@ -93,75 +93,119 @@ init_config() {
 	read pattern
 	[ -z "$pattern" ] && pattern="*"
 
-	echo "$pattern filter=encrypt diff=encrypt" >> $attrs
-	echo "[merge]" >> $attrs
-	echo "    renormalize=true" >> $attrs
+    _setup
+}
 
-	# Encryption
-	git config gitcrypt.salt "$SALT"
-	git config gitcrypt.pass "$PASS"
-	git config gitcrypt.cipher "$CIPHER"
+_init() {
+    eval `sed '/^ *#/d;s/:/ /;' < "$1" | while read key val; do echo "$key='$val'"; done`
+    _setup
+}
 
-	# Filters
-	git config filter.encrypt.smudge "gitcrypt smudge"
-	git config filter.encrypt.clean "gitcrypt clean"
-	git config diff.encrypt.textconv "gitcrypt diff"
+_setup() {
+    _cryptcheck
+
+    # Need a pattern
+    if [ -z "$pattern" ]; then
+        echo "Gitcrypt: filter pattern has not been configured"
+        exit 1
+    fi
+
+    # Need a attr
+    if [ -z "$pattern" ]; then
+        echo "Gitcrypt: filter attr has not been configured"
+        exit 1
+    fi
+
+    echo "$pattern filter=encrypt diff=encrypt" >> $attrs
+    echo "[merge]" >> $attrs
+    echo "    renormalize=true" >> $attrs
+
+    # Encryption
+    git config gitcrypt.salt "$SALT"
+    git config gitcrypt.pass "$PASS"
+    git config gitcrypt.cipher "$CIPHER"
+
+    # Filters
+    git config filter.encrypt.smudge "gitcrypt smudge"
+    git config filter.encrypt.clean "gitcrypt clean"
+    git config diff.encrypt.textconv "gitcrypt diff"
+
+    echo "SALT: $SALT" > .git/gitcrypt
+    echo "PASS: $PASS" >> .git/gitcrypt
+    echo "CIPHER: $CIPHER" >> .git/gitcrypt
+    echo "pattern: $pattern" >> .git/gitcrypt
+    echo "attrs: $attrs" >> .git/gitcrypt
+
+    echo "gitcrypt config has been saved to .git/gitcrypt"
 }
 
 _clean() {
-	# Encrypt using OpenSSL
-	openssl enc -base64 -$CIPHER -S "$SALT" -k "$PASS"
+    # Encrypt using OpenSSL
+    openssl enc -base64 -$CIPHER -S "$SALT" -k "$PASS"
 }
 
 _smudge() {
-	# If decryption fails, use `cat` instead
-	openssl enc -d -base64 -$CIPHER -k "$PASS" 2> /dev/null || cat
+    # If decryption fails, use `cat` instead
+    openssl enc -d -base64 -$CIPHER -k "$PASS" 2> /dev/null || cat
 }
 
 _diff() {
-	# If decryption fails, use `cat` instead
-	openssl enc -d -base64 -$CIPHER -k "$PASS" -in "$1" 2> /dev/null || cat "$1"
+    # If decryption fails, use `cat` instead
+    openssl enc -d -base64 -$CIPHER -k "$PASS" -in "$1" 2> /dev/null || cat "$1"
+}
+
+_cryptcheck() {
+    # Need a shared salt
+    if [ -z "$SALT" ]; then
+        echo "Gitcrypt: shared salt (gitcrypt.salt) has not been configured"
+        exit 1
+    fi
+
+    # Need a secure passphrase
+    if [ -z "$PASS" ]; then
+        echo "Gitcrypt: secure passphrase (gitcrypt.pass) has not been configured"
+        exit 1
+    fi
+
 }
 
 case "$1" in
-	clean|smudge|diff)
-		# Need a shared salt
-		SALT=$(git config gitcrypt.salt)
-		if [ -z "$SALT" ]; then
-			echo "Gitcrypt: shared salt (gitcrypt.salt) has not been configured"
-			exit 1
-		fi
+    clean|smudge|diff)
+        # Need a shared salt
+        SALT=$(git config gitcrypt.salt)
 
-		# Need a secure passphrase
-		PASS=$(git config gitcrypt.pass)
-		if [ -z "$PASS" ]; then
-			echo "Gitcrypt: secure passphrase (gitcrypt.pass) has not been configured"
-			exit 1
-		fi
+        # Need a secure passphrase
+        PASS=$(git config gitcrypt.pass)
 
-		# And a cipher mode
-		CIPHER=$(git config gitcrypt.cipher)
-		[ -z "$CIPHER" ] && CIPHER="$DEFAULT_CIPHER"
+        # And a cipher mode
+        CIPHER=$(git config gitcrypt.cipher)
+        [ -z "$CIPHER" ] && CIPHER="$DEFAULT_CIPHER"
 
-		# Execute command
-		_$1 "$2"
-		;;
-	init)
-		# Run setup commands
-		init_config
-		;;
-	version)
-		# Show version
-		echo "gitcrypt version $VERSION"
-		;;
-	*)
-		# Not a valid option
-    if [ -z "$1" ]; then
-      echo "Gitcrypt: available options: init, version"
-    else
-		  echo "Gitcrypt: command does not exist: $1"
-    fi
-		exit 1
-		;;
+        _cryptcheck
+
+        # Execute command
+        _$1 "$2"
+        ;;
+    init)
+        # Run setup commands
+        if [ -z "$2" ]; then
+            init_config
+        else
+            _$1 "$2"
+        fi
+        ;;
+    version)
+        # Show version
+        echo "gitcrypt version $VERSION"
+        ;;
+    *)
+        # Not a valid option
+        if [ -z "$1" ]; then
+            echo "Gitcrypt: available options: init, version"
+        else
+            echo "Gitcrypt: command does not exist: $1"
+        fi
+        exit 1
+        ;;
 esac
 exit 0
