Completly rewrite crypto-logic
* using masterkey for encrypt repo
* support for GPG masterkey encrypting
* support fot ssh key masterkey encrypting
* plain passphrase about to work

diff --git a/gitcrypt b/gitcrypt
--- a/gitcrypt
+++ b/gitcrypt
@@ -51,7 +51,7 @@ _debug() {
 
 
 _generate_masterkey() {
-  cat /dev/urandom | LC_ALL="C" tr -dc '!@#$%^&*()_A-Z-a-z-0-9' | head -c32
+  cat /dev/urandom | LC_ALL="C" tr -dc '!@#$%^&*()_A-Z-a-z-0-9' | head -c64
 }
 
 _master() {
@@ -61,9 +61,9 @@ _master() {
 _encrypt_masterkey() {
   local master=$(_master)
   if [ "$PASS" == "gpg" ]; then
-    echo _generate_masterkey | gpg --encrypt --armor > "$master"
+    echo $(_generate_masterkey) | gpg --encrypt --armor > "$master"
   else
-    echo _generate_masterkey | openssl enc -d -base64 -$CIPHER -k "$PASS" > "$master"
+    echo $(_generate_masterkey) | openssl enc -base64 -aes-256-cbc -k "$PASS" > "$master"
   fi
 }
 
@@ -74,7 +74,7 @@ _decrypt_masterkey() {
 	  if [ "$PASS" == "gpg" ]; then
 	    MKEY=$(cat "$master" | gpg --decrypt || die "can't decrypt masterkey")
 	  else
-		  MKEY=$(openssl enc -d -base64 -$CIPHER -k "$PASS" -in "$master" || die "can't decrypt masterkey")
+		  MKEY=$(openssl enc -d -base64 -aes-256-cbc -k "$PASS" -in "$master" || die "can't decrypt masterkey")
 	  fi
   done
 }
@@ -170,7 +170,7 @@ init_config() {
   	  git add $(_master)
   	  git commit -m "master key initilized"
     fi
-    _decrypt_masterkey
+    take_pass_from_cache
 
     git config gitcrypt.salt "$(_salt $MKEY)"
     git config gitcrypt.pass "$PASS"
@@ -181,36 +181,39 @@ init_config() {
 }
 
 
-take_pass_from_any() {
+take_pass_from_cache() {
     #expand ~/file to absolute filepath
-    PRIVATE_KEY=$(eval echo "${PASS}" 2> /dev/null)
-    if expr "$PRIVATE_KEY" : ".*\.pub" > /dev/null ; then
-		#remove .pu extension if any
-        PRIVATE_KEY=$(echo "$PRIVATE_KEY" | sed s/.pub//)
-		PRIVATE_KEY=`readlink -e "$PRIVATE_KEY"`
-    fi
+    #PRIVATE_KEY=$(eval echo "${PASS}" 2> /dev/null)
+    #if expr "$PRIVATE_KEY" : ".*\.pub" > /dev/null ; then
+	#	#remove .pu extension if any
+    #    PRIVATE_KEY=$(echo "$PRIVATE_KEY" | sed s/.pub//)
+	#	PRIVATE_KEY=`readlink -e "$PRIVATE_KEY"`
+    #fi
 
     #decrypt key and start watchdog for unencrypted file
-    if [[ -s "$PRIVATE_KEY" ]]; then
-        export GITCRYPT_KEY_ENCRYPTED="$PRIVATE_KEY"
-        PASS=$(gitcrypt-restore-key) || die "can't decrypt key"
-        _debug "= key decrypted"
-        unset GITCRYPT_KEY_ENCRYPTED
-    fi
+    #if [[ -s "$PRIVATE_KEY" ]]; then
+    #    export GITCRYPT_KEY_ENCRYPTED="$PRIVATE_KEY"
+    #    PASS=$(gitcrypt-restore-key) || die "can't decrypt key"
+    #    _debug "= key decrypted"
+    #    unset GITCRYPT_KEY_ENCRYPTED
+    #fi
+
+	export GITCRYPT_KEY_ENCRYPTED=$(_master)
+  MKEY=$(gitcrypt-restore-key "$PASS") || die "can't decrypt key"
 }
 
 _clean() {
-  _decrypt_masterkey
+	take_pass_from_cache
 	openssl enc -base64 -$CIPHER -S "$SALT" -k "$MKEY"
 }
 
 _smudge() {
-  _decrypt_masterkey
+	take_pass_from_cache
 	openssl enc -d -base64 -$CIPHER -k "$MKEY" 2> /dev/null || cat
 }
 
 _diff() {
-  _decrypt_masterkey
+	take_pass_from_cache
 	openssl enc -d -base64 -$CIPHER -k "$MKEY" -in "$1" 2> /dev/null || cat "$1"
 }
 
@@ -316,8 +319,6 @@ case "$1" in
         if [ -z "$PASS" ]; then
             die "Gitcrypt: secure passphrase (gitcrypt.pass) has not been configured"
         fi
-
-        MKEY=$(_decrypt_masterkey)
 
         # And a cipher mode
         CIPHER=$(git config gitcrypt.cipher)
